### PR TITLE
Accommodate additional file translations 

### PR DESCRIPTION
**Pull request by mauriciofaria**
Hi Rolf.
I still need some more file related functions...
What about an "additional" include file to accommodate user related stuff.
May I suggest adding a line to the include file:

#include letofile_additional.ch
And add an empty letofile_additional.ch file to the project.
So, one can add additional translations without touching the letofile.ch.

The functions I still need and what I did in the letofile_additional.ch is :

#if defined( __LETO_TRANSLATE_FILE_ALL )
#xtranslate CurDrive( [<x,...>] ) => leto_Udf( "HB_CurDrive", )
#xtranslate HB_CurDrive( [<x,...>] ) => leto_Udf( "HB_CurDrive", )
#xtranslate HB_OsDriveSeparator( [<x,...>] ) => leto_Udf( "HB_OsDriveSeparator", )
#xtranslate HB_OsPathSeparator( [<x,...>] ) => leto_Udf( "HB_OsPathSeparator", )
#xtranslate CURDIR( [<x,...>] ) => leto_Udf( "CURDIR", )
#xtranslate DiskName( [<x,...>] ) => leto_Udf( "DiskName", )
#xtranslate FileSeek( [<x,...>] ) => leto_Udf( "FileSeek", )
#xtranslate IsDisk( [<x,...>] ) => leto_Udf( "IsDisk", )
#xtranslate DIRNAME( [<x,...>] ) => leto_Udf( "DIRNAME", )
#xtranslate HB_IniWrite( [<x,...>] ) => leto_Udf( "HB_IniWrite", )
#xtranslate HB_IniRead( [<x,...>] ) => leto_Udf( "HB_IniRead", )
#xtranslate FileDelete( [<x,...>] ) => leto_Udf( "FileDelete", )
#xtranslate FLineCount( [<x,...>] ) => leto_Udf( "FLineCount", )
#xtranslate OrdKeyAdd( [<x,...>] ) => leto_Udf( "OrdKeyAdd", )
#endif

Regards,
Maurício Ventura Faria

### CODE REVIEW

**Comment by mauriciofaria** [comment]
I Also added letofile.ch to letodb.hbc.

**Comment by mauriciofaria** [comment]
Also I changed the default name for the service executable to letodbService.
This is because sometimes one may need both the service and non service executables and this avoid some confusion.

**Comment by mauriciofaria** [comment]
I will try to explain some of the additional file functions I need.

   #xtranslate HB_OsDriveSeparator( [<x,...>] )   =>  leto_Udf( "HB_OsDriveSeparator", <x> )
   #xtranslate HB_OsPathSeparator( [<x,...>] )    =>  leto_Udf( "HB_OsPathSeparator", <x> )
 
I need to run the same system in Windows and Linux, depending on the customer needs and path and drive separators are different in those systems. Sometimes I need to construct the full path name of a file, sometimes referencing a file outside the application context in order to, for example, communicate with another application via text file exchange, where I need to point where to write or read those files.

   #xtranslate CurDrive( [<x,...>] )              =>  leto_Udf( "HB_CurDrive", <x> )
   #xtranslate HB_CurDrive( [<x,...>] )           =>  leto_Udf( "HB_CurDrive", <x> )
   #xtranslate CURDIR( [<x,...>] )                =>  leto_Udf( "CURDIR", <x> )
   #xtranslate DiskName( [<x,...>] )              =>  leto_Udf( "DiskName", <x> )
   #xtranslate DIRNAME( [<x,...>] )               =>  leto_Udf( "DIRNAME", <x> )

This ones are also related to the above.

   #xtranslate FileDelete( [<x,...>] )            =>  leto_Udf( "FileDelete", <x> )

Deleting a file is also related to the above.
 
   #xtranslate HB_IniWrite( [<x,...>] )           =>  leto_Udf( "HB_IniWrite", <x> )
   #xtranslate HB_IniRead( [<x,...>] )            =>  leto_Udf( "HB_IniRead", <x> )

This are Harbour native functions to manipulate INI files, a common task.

**Comment by mauriciofaria** [comment]
#xtranslate OrdKeyAdd( [<x,...>] )             =>  leto_Udf( "OrdKeyAdd", <x> )
 
Not rigorously a file function.
This is kind of basic index file manipulation function, I think it should be part of any RDD.

**Comment by elchs** [comment]
Hi Mauricio,

there is an extended long answer from January at Harbour user forum,
why i rejected parts of your old pull request and implemented what makes sense.
In the above pull request are these parts i won't implement

I just added one more comment to the post from January,
to pull it up the in the forum list -- have a look for that ...

best regards
Rolf

**Comment by mauriciofaria** [comment]
Hi Rolf.
 
I agree and respect your position on not implementing all I asked before.
 
The comments I made was only explaining why I needed some stuff, but these are my specific needs and I can manage it in other ways.

But in this pull request I add nothing about that old stuff, I just add a way to the user add things he needs without touching the original code.
 
For example, to accommodate my personal needs I have to change letofile.ch and every time I synchronize with the repository I have to pay attention to these changes.
Adding the letofile_additional.ch to the project accommodate user specific needs in an elegant way ( IMHO ). I saw this approach the first time in the Asterisk open source PABX project and liked it.
I added an empty letofile_additional.ch file to the project, so, no changes in the project logic at all.
 
The other changes also dos not change anything in the project logic.

In letodb.hbc I only added a reference to include the letofile.ch file.  If the environment isn't set to use it it will be just ignored.

In  letodbsvc.hbp I changed the resulting executable name in order to it be different on service and console mode. Sometimes one could need both and with different names it is easier.
 
These are only suggestions, If you do not agree just drop any of this, I am really ok on it.
 
And I am really grateful with your job on LetoDBF, thanks !!!
 
Regards, 
Maurício Faria

**Pull request closed without merging**
